// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DCxHF7XhxhqvY5HLFhwJdmTF6g2-heM',
    appId: '1:122227190545:web:4eee55a1ad2b45dd6a3ab0',
    messagingSenderId: '122227190545',
    projectId: 'flutter-exemplar2',
    authDomain: 'flutter-exemplar2.firebaseapp.com',
    storageBucket: 'flutter-exemplar2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicJODYm3D4xBc4yw6VKVYMj-4eUf2HHo',
    appId: '1:122227190545:android:f7280f0225c3cdb26a3ab0',
    messagingSenderId: '122227190545',
    projectId: 'flutter-exemplar2',
    storageBucket: 'flutter-exemplar2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCamahK5FAujHgcK-ZZb1ZwDPbdbgTO9Wg',
    appId: '1:122227190545:ios:0605fa8f377ae38e6a3ab0',
    messagingSenderId: '122227190545',
    projectId: 'flutter-exemplar2',
    storageBucket: 'flutter-exemplar2.appspot.com',
    iosClientId: '122227190545-rlooqomh92ebu77g0u1sj2i394162u89.apps.googleusercontent.com',
    iosBundleId: 'com.example.exemplar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCamahK5FAujHgcK-ZZb1ZwDPbdbgTO9Wg',
    appId: '1:122227190545:ios:0605fa8f377ae38e6a3ab0',
    messagingSenderId: '122227190545',
    projectId: 'flutter-exemplar2',
    storageBucket: 'flutter-exemplar2.appspot.com',
    iosClientId: '122227190545-rlooqomh92ebu77g0u1sj2i394162u89.apps.googleusercontent.com',
    iosBundleId: 'com.example.exemplar',
  );
}
